# Generated by Django 4.1.7 on 2023-02-27 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.TextField(default='address'),
            preserve_default=False,
        ),
    ]
