# Generated by Django 4.1.7 on 2023-04-05 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_intent_id',
            field=models.CharField(default='1', max_length=50),
            preserve_default=False,
        ),
    ]
