# Generated by Django 4.1.7 on 2023-04-07 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_order_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('U', 'Uninitiated'), ('R', 'Creating'), ('W', 'Waiting'), ('F', 'Failed'), ('C', 'Completed')], default='U', max_length=1),
        ),
    ]
