# Generated by Django 4.1.7 on 2023-04-11 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_collection_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Collection',
            new_name='Category',
        ),
    ]
