# Generated by Django 4.1.7 on 2023-04-11 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_rename_collection_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='collection',
            new_name='category',
        ),
    ]
