# Generated by Django 4.1.7 on 2023-04-11 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_rename_collection_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
