# Generated by Django 4.1.7 on 2023-04-14 04:11

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_alter_category_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=django_fsm.FSMField(choices=[('a', 'Awaiting payment'), ('b', 'Processed'), ('c', 'Shipped'), ('d', 'Completed'), ('p', 'Cancelled')], default='a', max_length=1),
        ),
    ]
