# Generated by Django 4.1.7 on 2023-04-14 04:30

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_remove_order_payment_status_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_reference',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=django_fsm.FSMField(choices=[('a', 'Awaiting payment'), ('b', 'Processed'), ('c', 'Shipped'), ('d', 'Completed'), ('p', 'Cancelled')], default='a', max_length=1, protected=True),
        ),
    ]
