# Generated by Django 4.1.7 on 2023-06-26 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_featuredproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', unique=True),
        ),
    ]
