# Generated by Django 4.1.7 on 2023-06-26 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_candleproduct_alter_cartitem_product_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CandleProduct',
            new_name='Product',
        ),
    ]
