# Generated by Django 4.1.7 on 2023-06-26 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_inventory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='maximum_burning_time',
            new_name='burning_time',
        ),
        migrations.RemoveField(
            model_name='product',
            name='minimum_burning_time',
        ),
    ]
