# Generated by Django 4.1.7 on 2023-07-07 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_featuredproduct_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
